version: '3'
services:
  vue-client:
    build: ./client
    command: npm start
    ports:
      - "8080:8080" 

  node-server:
    build: ./server
    command: npm start
    ports:
      - "9000:9000"   
    links:
      - mongo  
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"    